---
- name: "Create temporary download directory"
  tempfile:
    state: directory
    suffix: .terraform
  register: download_dir

- name: "Download Terraform {{ version }}"
  unarchive:
    src: "https://releases.hashicorp.com/terraform/{{ version }}/terraform_{{ version }}_linux_amd64.zip"
    dest: "{{ download_dir.path }}"
    remote_src: yes

- name: "Copy Terraform executable to bin directory ({{ terraform_executable_dir }})"
  copy:
    src: "{{ download_dir.path }}/terraform"
    dest: "{{ terraform_executable_path }}"
    mode: '0755'
    remote_src: yes

- name: "Remove temporary download directory"
  file:
    path: "{{ download_dir.path }}"
    state: absent
  when: download_dir.path is defined

- name: "Create alternative for Terraform {{ version }}{{ (default == 'true') | ternary(' (default version)', '') }}"
  alternatives:
    name: terraform
    link: "{{ terraform_alternative_path }}"
    path: "{{ terraform_executable_path }}"
    priority: "{{ (default == 'true') | ternary(100, 0) }}"