---
# tasks file for ubuntu/18.04/terraform

- set_fact:
    terraform_executable_dir: "/usr/local/bin"

- set_fact:
    terraform_executable_path: "{{ terraform_executable_dir }}/terraform{{ version }}"
    terraform_alternative_path: "{{ terraform_executable_dir }}/terraform"

- name: "check if Terraform {{ version }} has been already downloaded"
  stat:
    path: "{{ terraform_executable_path }}"
  register: stat_result

- include: install_terraform.yml
  when: stat_result.stat.exists == False
